# Generated by Django 5.1.4 on 2025-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrivetechapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="products",
            field=models.CharField(max_length=255),
        ),
    ]
